Mofab\MetricBundle\Entity\Metric:
  type: entity
  table: met_metric
  id:
    id:
      type: integer
      nullable: false
      column: met_id
      id: true
      generator:
        strategy: IDENTITY
  fields:
    application:
      type: string
      nullable: false
      length: 255
      fixed: false
      column: met_application
    script:
      type: string
      nullable: false
      length: 255
      fixed: false
      column: met_script
    unit:
      type: string
      nullable: false
      length: 255
      fixed: false
      column: met_unit
    quantity:
      type: integer
      nullable: false
      options:
        default: 0
      column: met_quantity
    memory:
      type: integer
      nullable: false
      options:
        default: 0
      column: met_memory
    completed:
      type: boolean
      nullable: false
      default: false
      column: met_completed
    added:
      type: float
      precision: 14
      scale: 4
      nullable: false
      column: met_added
    updated:
      type: float
      precision: 14
      scale: 4
      nullable: true
      column: met_updated

